name: Validar HTML y CSS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # Validación HTML
      - name: Validar HTML con w3c-validator
        uses: docker://ghcr.io/validator/validator:latest
        with:
          args: >
            --user-agent "Validator.nu/LV"
            --skip-non-html
            --Werror
            ./index.html

      # Validación CSS
      - name: Validar CSS con css-validator
        uses: docker://ghcr.io/w3c/css-validator:latest
        with:
          args: >
            java -jar /vnu/css-validator.jar
            -v 1
            -profile css3svg
            -warning 2
            ./styles.css
